common/models/Request.php
<?php

namespace common\models;

use yii\behaviors\TimestampBehavior;
use yii\db\ActiveQuery;
use yii\db\ActiveRecord;

/**
 * @property integer $id
 * @property string $comment
 * @property string $customer_full_name
 * @property string $name
 * @property string $phone
 * @property float|null $price
 * @property int $product_id
 * @property int $status
 * @property integer $created_at
 * @property integer $updated_at
 * @property Product $product
 * @property RequestHistory[] $history
 */
class Request extends ActiveRecord
{
    public const STATUS_NEW = 1;
    public const STATUS_ACCEPTED = 2;
    public const STATUS_REJECTED = 3;
    public const STATUS_DEFECT = 4;

    public const STATUS_LIST = [
        self::STATUS_NEW => 'Новая',
        self::STATUS_ACCEPTED => 'Принята',
        self::STATUS_REJECTED => 'Отказана',
        self::STATUS_DEFECT => 'Брак',
    ];

    /**
     * {@inheritdoc}
     */
    public static function tableName(): string
    {
        return '{{%request}}';
    }

    /**
     * {@inheritdoc}
     */
    public function behaviors(): array
    {
        return [
            TimestampBehavior::class,
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function rules(): array
    {
        return [
            ['comment', 'required'],
            ['comment', 'string', 'max' => 1024],

            ['name', 'string', 'max' => 256],
            ['name', 'filter', 'skipOnError' => false, 'filter' => fn($value) => $value === '' ? null : $value],

            ['phone', 'required'],
            ['phone', 'string', 'max' => 256],

            ['price', 'double'],
            ['price', 'filter', 'skipOnError' => false, 'filter' => fn($value) => $value === '' ? null : (float) $value],

            ['customer_full_name', 'required'],
            ['customer_full_name', 'string', 'max' => 256],

            ['product_id',  'required'],
            ['product_id', 'exist', 'targetClass' => Product::class, 'targetAttribute' => ['product_id' => 'id']],
            ['product_id', 'filter', 'skipOnError' => false, 'filter' => fn($value) => $value === '' ? null : (int) $value],

            ['status', 'required'],
            ['status', 'default', 'value' => self::STATUS_NEW],
            ['status', 'in', 'range' => array_keys(self::STATUS_LIST)],
            ['status', 'filter', 'skipOnError' => false, 'filter' => fn($value) => $value === '' ? null : (int) $value],
        ];
    }

    public function attributeLabels(): array
    {
        return [
            'id'                 => 'Ид.',
            'customer_full_name' => 'Клиент',
            'name'               => 'Наименование',
            'phone'              => 'Телефон',
            'price'              => 'Цена',
            'product'            => 'Продукт',
            'product_id'         => 'Продукт',
            'comment'            => 'Комментарий',
            'status'             => 'Статус',
            'created_at'         => 'Дата создания',
            'updated_at'         => 'Дата изменения',
        ];
    }

    public function statusName(): string
    {
        return self::STATUS_LIST[$this->status] ?? '';
    }

    public function formName(): string
    {
        return '';
    }

    public function changeStatus(int $status)
    {
        $this->status = $status;

        return $this;
    }

    public function getNextStatuses(): array
    {
        return array_filter(
            array_keys(self::STATUS_LIST),
            fn($status) => !in_array($status, [self::STATUS_NEW, $this->status])
        );
    }

    public function getProduct(): ActiveQuery
    {
        return $this->hasOne(Product::class, ['id' => 'product_id']);
    }

    public function getRequestHistory(): ActiveQuery
    {
        return $this->hasMany(RequestHistory::class, ['id' => 'request_id']);
    }
}

common/models/RequestForm.php
<?php

namespace common\models;

class RequestForm extends Form
{
    public ?int $id = null;
    public ?string $name = null;
    public ?string $comment = null;
    public ?string $customer_full_name = null;
    public ?string $phone = null;
    public ?string $price = null;
    public ?int $product_id = null;
    public ?int $status = null;

    public static function createByRequest(Request $request): RequestForm
    {
        $form = new self;
        $form->id = $request->id;
        $form->name = $request->name;
        $form->comment = $request->comment;
        $form->customer_full_name = $request->customer_full_name;
        $form->phone = $request->phone;
        $form->price = $request->price;
        $form->product_id = $request->product_id;
        $form->status = $request->status;

        return $form;
    }

    /**
     * {@inheritdoc}
     */
    public function rules(): array
    {
        return [
            ...$this->rulesComment(),
            ...$this->rulesCustomerName(),
            ...$this->rulesName(),
            ...$this->rulesPhone(),
            ...$this->rulesPrice(),
            ...$this->rulesProductId(),
            ...$this->rulesStatus(),
        ];
    }

    public function attributeLabels(): array
    {
        return [
            'id'                 => 'Ид.',
            'customer_full_name' => 'Клиент',
            'name'               => 'Наименование',
            'phone'              => 'Телефон',
            'price'              => 'Цена',
            'product_id'         => 'Продукт',
            'status'             => 'Статус',
            'comment'            => 'Комментарий',
            'created_at'         => 'Дата создания',
            'updated_at'         => 'Дата изменения',
        ];
    }

    public function formName(): string
    {
        return '';
    }

    public function getStatusList(): array
    {
        return Request::STATUS_LIST;
    }

    public function getProductList(): array
    {
        return Product::find()
            ->select(['name'])
            ->indexBy('id')
            ->column();
    }

    protected function rulesName(): array
    {
        return [
            ['name', 'string', 'max' => 256],
        ];
    }

    protected function rulesProductId(): array
    {
        return [
            ['product_id', 'required'],
            ['product_id', 'exist', 'targetClass' => Product::class, 'targetAttribute' => ['product_id' => 'id']],
        ];
    }

    protected function rulesStatus(): array
    {
        return [
            ['status', 'required'],
            ['status', 'in', 'range' => array_keys($this->getStatusList())],
        ];
    }

    protected function rulesCustomerName(): array
    {
        return [
            ['customer_full_name', 'required'],
            ['customer_full_name', 'string', 'max' => 256],
        ];
    }

    protected function rulesPhone(): array
    {
        return [
            ['phone', 'required'],
            ['phone', 'string', 'max' => 256],
        ];
    }

    protected function rulesPrice(): array
    {
        return [
            ['phone', 'required'],
            ['phone', 'string', 'max' => 256],
        ];
    }

    protected function rulesComment(): array
    {
        return [
            ['comment', 'required'],
            ['comment', 'string', 'max' => 1024],
        ];
    }
}

frontend/models/RequestForm.php
<?php

namespace frontend\models;

class RequestForm extends \common\models\RequestForm
{
    public function rules(): array
    {
        return [
            ...$this->rulesComment(),
            ...$this->rulesCustomerName(),
            ...$this->rulesPhone(),
            ...$this->rulesProductId(),
        ];
    }

    public function attributeLabels(): array
    {
        return [
            ...parent::attributeLabels(),
            'customer_full_name' => 'ФИО',
        ];
    }
}

backend/controllers/RequestController.php
<?php

namespace backend\controllers;

use common\models\RequestForm;
use common\exceptions\InvalidFormException;
use common\services\RequestService;
use yii\web\Controller;
use yii\web\Response;

class RequestController extends Controller
{
    private RequestService $service;

    public function __construct($id, $module, $config = [])
    {
        parent::__construct($id, $module, $config);

        $this->service = new RequestService();
    }

    public function actionIndex(): string
    {
        $data = [
            'perPage' => $this->request->get('per-page'),
            'page' => $this->request->get('page'),
            'sortBy' => $this->request->get('sort-by'),
            'sortOrder' => $this->request->get('sort-order'),
        ];

        return $this->render('grid', $this->service->list($data));
    }

    public function actionView(?int $id): string|Response
    {
        return $this->render('detail', [
            'request' => $this->service->get($id)
        ]);
    }

    public function actionCreate(): string|Response
    {
        if ($this->request->isGet) {
            return $this->render('form', ['request' => new RequestForm]);
        }
        try {
            $this->service->create(
                $this->request->post()
            );
        } catch (InvalidFormException $e) {
            return $this->render('form', ['request' => $e->getForm()]);
        }

        return $this->redirect(['request/index']);
    }

    public function actionUpdate(int $id): string|Response
    {
        $form = RequestForm::createByRequest(
            $this->service->get($id)
        );
        if ($this->request->isGet) {
            return $this->render('form', ['request' => $form]);
        }

        try {
            $this->service->update(
                $id,
                $this->request->post()
            );
        } catch (InvalidFormException $e) {
            return $this->render('form', ['request' => $e->getForm()]);
        }

        return $this->redirect(['request/index']);
    }

    public function actionDelete(int $id): Response
    {
        $this->service->delete($id);

        return $this->redirect(['request/index']);
    }

    public function actionChangeStatus(int $id, int $status): Response
    {
        $this->service->changeStatus($id, $status);

        return $this->redirect(['request/index']);
    }

    public function actionHistory(int $id): string
    {
        $data = [
            'perPage' => $this->request->get('per-page'),
            'page' => $this->request->get('page'),
            'sortBy' => $this->request->get('sort-by'),
            'sortOrder' => $this->request->get('sort-order'),
        ];

        return $this->render('history', $this->service->history($id, $data));
    }

    public function actionExportCsv(): Response
    {
        return $this->response->sendContentAsFile($this->service->generateCsv(), 'export.csv', [
            'mimeType' => 'application/csv',
            'inline'   => false
        ]);
    }
}

frontend/controllers/RequestController.php
<?php

namespace frontend\controllers;

use common\services\RequestService;
use common\exceptions\InvalidFormException;
use common\models\Request;
use frontend\models\RequestForm;
use Yii;
use yii\web\Controller;
use yii\web\Response;

class RequestController extends Controller
{
    private RequestService $service;

    public function __construct($id, $module, $config = [])
    {
        parent::__construct($id, $module, $config);

        $this->service = new RequestService();
    }

    public function actionIndex(): Response|string
    {
        $form = new RequestForm;
        if ($this->request->isPost) {
            $form->load($this->request->post());
            if ($form->validate() && $this->createRequest()) {
                Yii::$app->session->setFlash('success', 'Ваша заявка успешно отправлена.');
                return $this->redirect('/request');
            }
            Yii::$app->session->setFlash('error', 'Ошибка отправки формы.');
        }

        return $this->render('form', [
            'request' => $form,
        ]);
    }

    private function createRequest(): bool
    {
        $data = $this->request->post();
        $data['status'] = Request::STATUS_NEW;

        try {
            $this->service->create($data);
        } catch (InvalidFormException) {
            return false;
        }
        return true;
    }
}

backend/views/request/detail.php
<?php

use common\models\Request;
use yii\widgets\DetailView;

/** @var Request $request */
/** @var yii\web\View $this */

$this->title = "Заявка #$request->id";
$this->params['breadcrumbs'][] = ['url' => '/request', 'label' => 'Заявки'];
$this->params['breadcrumbs'][] = $this->title;
?>
<h1 class="card-title pt-1 pb-4"><?php echo $this->title; ?></h1>
<div class="user-default-index">
    <?php echo DetailView::widget([
        'model' => $request,
        'attributes' => [
            'id',
            'name',
            'customer_full_name',
            'phone',
            'comment:ntext',
            'price',
            [
                'attribute' => 'status',
                'value' => fn(Request $request) => $request->statusName(),
            ],
            [
                'label' => 'Продукт',
                'value' => fn(Request $request) => $request->product->name,
            ],
            'created_at:datetime',
            'updated_at:datetime',
        ],
    ]); ?>
</div>

backend/views/request/form.php
<?php

/** @var yii\web\View $this */
/* @var RequestForm $request */

use common\models\RequestForm;
use yii\bootstrap5\ActiveForm;
use yii\helpers\Html;

$title = !$request->id ? 'Создание заявки' : "Редактирование заявки #$request->id";
$buttonText = !$request->id ? 'Создать заявку' : "Сохранить изменения";

$this->title = "$title";
$this->params['breadcrumbs'][] = ['url' => '/request', 'label' => 'Заявки'];
$this->params['breadcrumbs'][] = $this->title;
?>
<h1 class="card-title pt-1 pb-4"><?php echo $this->title; ?></h1>
<?php $form = ActiveForm::begin(); ?>

    <?= $form->field($request, 'name')->textInput(); ?>
    <?= $form->field($request, 'customer_full_name')->textInput(); ?>
    <?= $form->field($request, 'status')->dropDownList($request->getStatusList()); ?>
    <?= $form->field($request, 'product_id')->dropDownList($request->getProductList()); ?>
    <?= $form->field($request, 'price')->textInput(); ?>
    <?= $form->field($request, 'phone')->textInput(); ?>
    <?= $form->field($request, 'comment')->textarea(); ?>

    <div class="form-group">
        <?= Html::submitButton($buttonText, ['class' => 'btn btn-primary']) ?>
    </div>

<?php ActiveForm::end(); ?>

backend/views/request/grid.php
<?php

use common\foundation\rbac\Permission;
use common\models\Request;
use yii\bootstrap5\ButtonDropdown;
use yii\data\ArrayDataProvider;
use yii\grid\ActionColumn;
use yii\grid\GridView;
use yii\grid\SerialColumn;
use yii\helpers\Html;

/* @var Request[] $data */
/* @var array $pager */

$this->title = 'Список заявок';
$this->params['breadcrumbs'][] = $this->title;
?>
<h1 class="card-title pt-1 pb-4"><?php echo $this->title; ?></h1>
<div class="user-default-index">
    <?php if (Yii::$app->user->can(Permission::REQUEST_CREATE)): ?>
        <div class="pt-1 pb-2">
            <?php echo Html::a('Создать заявку', ['/request/create'], [
                'class' => 'btn btn-primary grid-button'
            ]); ?>
            <?php echo Html::a('Экспорт СSV', ['/request/export-csv'], [
                'class' => 'btn btn-default grid-button',
                'download'
            ]); ?>
        </div>
    <?php endif; ?>
    <?php echo GridView::widget([
        'dataProvider' => new ArrayDataProvider(['allModels' => $data]),
        'columns' => [
            ['class' => SerialColumn::class],

            [
                'label' => 'Ид.',
                'attribute' => 'id',
            ],
            [
                'label' => 'Наименование',
                'attribute' => 'name',
            ],
            [
                'label' => 'Клиент',
                'attribute' => 'customer_full_name',
            ],
            [
                'label' => 'Телефон',
                'attribute' => 'phone',
            ],
            [
                'label' => 'Комментарий',
                'attribute' => 'comment',
                'format' => 'ntext',
            ],
            [
                'label' => 'Цена',
                'attribute' => 'price',
            ],
            [
                'attribute' => 'status',
                'value' => fn(Request $request) => $request->statusName(),
            ],
            [
                'label' => 'Продукт',
                'value' => fn(Request $request) => $request->product->name,
            ],
            [
                'label' => 'Дата создания',
                'attribute' => 'created_at',
                'format' => 'datetime',
            ],
            [
                'class' => ActionColumn::class,
                'visibleButtons' => [
                    'view' => Yii::$app->user->can(Permission::REQUEST_VIEW),
                    'update' => Yii::$app->user->can(Permission::REQUEST_UPDATE),
                    'delete' => Yii::$app->user->can(Permission::REQUEST_DELETE),
                    'change-status' => Yii::$app->user->can(Permission::REQUEST_UPDATE),
                    'history' => Yii::$app->user->can(Permission::REQUEST_HISTORY_VIEW),
                ],
                'urlCreator' => fn($action, $model) => [$action, 'id' => $model['id']],
                'template' => '{view} {update} {delete} {history} {change-status}',
                'buttons' => [
                    'history' => fn($url) => Html::a(
                        '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" style="display:inline-block;font-size:inherit;height:1em;overflow:visible;vertical-align:-.125em;width:1.125em"><path fill="currentColor" d="M448 360V24c0-13.3-10.7-24-24-24H96C43 0 0 43 0 96v320c0 53 43 96 96 96h328c13.3 0 24-10.7 24-24v-16c0-7.5-3.5-14.3-8.9-18.7-4.2-15.4-4.2-59.3 0-74.7 5.4-4.3 8.9-11.1 8.9-18.6zM128 134c0-3.3 2.7-6 6-6h212c3.3 0 6 2.7 6 6v20c0 3.3-2.7 6-6 6H134c-3.3 0-6-2.7-6-6v-20zm0 64c0-3.3 2.7-6 6-6h212c3.3 0 6 2.7 6 6v20c0 3.3-2.7 6-6 6H134c-3.3 0-6-2.7-6-6v-20zm253.4 250H96c-17.7 0-32-14.3-32-32 0-17.6 14.4-32 32-32h285.4c-1.9 17.1-1.9 46.9 0 64z"/></svg>',
                        $url,
                        ['title' => 'История изменения']
                    ),
                    'change-status' => fn($url, Request $model) => ButtonDropdown::widget([
                        'label' => 'Изменить статус',
                        'dropdown' => [
                            'items' => array_map(
                                fn($status) => [
                                    'label' => Request::STATUS_LIST[$status],
                                    'url' => $url + ['status' => $status],
                                ],
                                $model->getNextStatuses()
                            )
                        ],
                    ]),
                ]
            ],
        ],
    ]); ?>
</div>

backend/views/request/history.php
<?php

use common\models\Request;
use common\models\RequestHistory;
use yii\data\ArrayDataProvider;
use yii\grid\GridView;

/* @var Request $request */
/* @var RequestHistory[] $data */
/* @var array $pager */

$this->title = "История изменений заявки #$request->id";
$this->params['breadcrumbs'][] = ['url' => '/request', 'label' => 'Заявки'];
$this->params['breadcrumbs'][] = $this->title;
?>
<h1 class="card-title pt-1 pb-4"><?php echo $this->title; ?></h1>
<div class="user-default-index">
    <?php echo GridView::widget([
        'dataProvider' => new ArrayDataProvider(['allModels' => $data]),
        'columns' => [
            [
                'label' => 'Ип.',
                'attribute' => 'id',
            ],
            [
                'label' => 'Статус',
                'value' => fn(RequestHistory $history) => $history->getFillDiff()->getStatusName() ?: '',
            ],
            [
                'label' => 'Наименование',
                'value' => fn(RequestHistory $history) => $history->getFillDiff()->getName() ?: '',
            ],
            [
                'label' => 'ФИО Клиента',
                'value' => fn(RequestHistory $history) => $history->getFillDiff()->getCustomerFullName() ?: ''
            ],
            [
                'label' => 'Телефон',
                'value' => fn(RequestHistory $history) =>  $history->getFillDiff()->getPhone() ?: ''
            ],
            [
                'label' => 'Дата',
                'value' => function(RequestHistory $history) {
                    $time = $history->getFillDiff()->getCreatedAt();
                    if (! $time) {
                        return '';
                    }
                    return \Yii::$app->formatter->asDatetime($time);
                },
            ],
            [
                'label' => 'Цена',
                'value' => fn(RequestHistory $history) => $history->getFillDiff()->getPrice() ?? '',
            ],
            [
                'label' => 'Продукт',
                'value' => fn(RequestHistory $history) => $history->getFillDiff()->getProductName() ?? '',
            ],
            [
                'label' => 'Комментарий',
                'value' => fn(RequestHistory $history) => $history->getFillDiff()->getComment() ?? '',
            ],
            [
                'label' => 'Пользователь',
                'attribute' => 'user.username',
            ],
            [
                'label' => 'Дата изменения',
                'attribute' => 'created_at',
                'format' => 'datetime',
            ],
        ],
    ]); ?>
</div>